// examples/qq_line/match/Example.svelte
<script lang="ts">
  import {
    GeomQqLine,
    GGPlot,
    Inspect,
    Labs,
    ThemeMinimal,
  } from "@ggts-sh/svelte";

  import { shortSample } from "./data.js";
</script>

<GGPlot data={shortSample} aes={{ sample: "value" }} width={640} height={400}>
  <GeomQqLine linewidth={3.2} alpha={1} aes={{ color: { value: "#1a202c" } }} />
  <ThemeMinimal />
  <Labs
    title="Q–Q reference line"
    subtitle="Line through the sample/theoretical quartile match"
    x="Theoretical quantile"
    y="Sample quantile"
  />
  <Inspect mode="x" pin />
</GGPlot>

// examples/histogram/basic/Example.tsx
"use client";

import {
  GeomHistogram,
  GeomRule,
  GGPlot,
  Inspect,
  Labs,
  ThemeFivethirtyeight,
} from "@ggts-sh/react";

import { michelson } from "./data.js";

export default function MichelsonHistogram() {
  return (
    <GGPlot
      data={michelson}
      aes={{ x: "velocity" }}
      width={640}
      height={400}
      ariaLabel="Histogram of a hundred experimental runs"
    >
      <GeomHistogram binwidth={40} />
      <GeomRule xintercept={734.5} linewidth={1.2} aes={{ color: { value: "#d14d41" } }} />
      <ThemeFivethirtyeight />
      <Labs
        title="Histogram of a hundred experimental runs"
        subtitle="Speed of light, km/s less 299,000"
        x="Velocity (km/s − 299,000)"
        y="Runs"
      />
      <Inspect mode="exact" pin />
    </GGPlot>
  );
}
