// examples/point/scatter-color/Example.tsx
"use client";

import {
  GeomPoint,
  GGPlot,
  GuideLegend,
  Inspect,
  Labs,
  ScaleColorDiscrete,
  ThemeFew,
} from "@ggts-sh/react";

import { guerry } from "./data.js";

export default function GuerryScatter() {
  return (
    <GGPlot
      data={guerry}
      aes={{ x: "literacy", y: "crimePersons", color: "region" }}
      width={640}
      height={400}
      ariaLabel="Two measures coloured by region"
    >
      <GeomPoint size={3} />
      <ScaleColorDiscrete scheme="observable10" />
      <ThemeFew />
      <GuideLegend channel="color" focus />
      <Labs
        title="Two measures coloured by region"
        subtitle="Literacy and crime by French department"
        x="Literate conscripts (%)"
        y="Population per crime against persons"
        color="Region"
      />
      <Inspect mode="xy" pin maxDistance={24} />
    </GGPlot>
  );
}

// examples/point/jitter/Example.svelte
<script lang="ts">
  import {
    GeomPoint,
    GGPlot,
    GuideNone,
    Inspect,
    Labs,
    ScaleColorDiscrete,
    ThemeClean,
  } from "@ggts-sh/svelte";

  import { fastfoodMenu } from "./data.js";
</script>

<GGPlot
  data={fastfoodMenu}
  aes={{ x: "restaurant", y: "calories", color: "restaurant" }}
  width={640}
  height={400}
>
  <GeomPoint
    position="jitter"
    positionParams={{ width: 0.22, height: 0 }}
    alpha={0.65}
  />
  <ScaleColorDiscrete scheme="observable10" />
  <ThemeClean />
  <GuideNone channel="color" />
  <Labs
    title="Calories by restaurant, with jitter"
    subtitle="Horizontal jitter spreads marks that share a restaurant"
    x="Restaurant"
    y="Calories"
  />
  <Inspect mode="xy" pin maxDistance={24} />
</GGPlot>
