// examples/jitter/basic/Example.tsx
"use client";

import {
  GeomJitter,
  GGPlot,
  GuideNone,
  Inspect,
  Labs,
  ScaleColorDiscrete,
  ThemeClean,
} from "@ggts-sh/react";

import { fastfoodMenu } from "./data.js";

export default function FastfoodJitter() {
  return (
    <GGPlot
      data={fastfoodMenu}
      aes={{ x: "restaurant", y: "calories", color: "restaurant" }}
      width={640}
      height={400}
      ariaLabel="Menu calories, spread so items do not stack"
    >
      <GeomJitter width={0.22} height={0} alpha={0.65} />
      <ScaleColorDiscrete scheme="observable10" />
      <ThemeClean />
      <GuideNone channel="color" />
      <Labs
        title="Menu calories, spread so items do not stack"
        subtitle="Each point is one entrée. Jitter separates items that share a restaurant"
        x="Restaurant"
        y="Calories"
      />
      <Inspect mode="xy" pin maxDistance={24} />
    </GGPlot>
  );
}

// examples/point/jitter/Example.svelte
<script lang="ts">
  import {
    GeomPoint,
    GGPlot,
    GuideNone,
    Inspect,
    Labs,
    ScaleColorDiscrete,
    ThemeClean,
  } from "@ggts-sh/svelte";

  import { fastfoodMenu } from "./data.js";
</script>

<GGPlot
  data={fastfoodMenu}
  aes={{ x: "restaurant", y: "calories", color: "restaurant" }}
  width={640}
  height={400}
>
  <GeomPoint
    position="jitter"
    positionParams={{ width: 0.22, height: 0 }}
    alpha={0.65}
  />
  <ScaleColorDiscrete scheme="observable10" />
  <ThemeClean />
  <GuideNone channel="color" />
  <Labs
    title="Calories by restaurant, with jitter"
    subtitle="Horizontal jitter spreads marks that share a restaurant"
    x="Restaurant"
    y="Calories"
  />
  <Inspect mode="xy" pin maxDistance={24} />
</GGPlot>
