// examples/vline/cutoff/Example.tsx
"use client";

import { GeomPoint, GeomVline, GGPlot, Inspect, Labs, ThemeMinimal } from "@ggts-sh/react";

import { earthDensity } from "./data.js";

export default function EarthDensityCutoff() {
  return (
    <GGPlot
      data={earthDensity}
      aes={{ x: "trial", y: "density" }}
      width={640}
      height={400}
      ariaLabel="One vertical cutoff"
    >
      <GeomPoint size={2.2} alpha={0.55} />
      <GeomVline xintercept={6.5} linewidth={2.6} aes={{ color: { value: "#d4615c" } }} />
      <ThemeMinimal />
      <Labs
        title="One vertical cutoff"
        subtitle="Wire changed after this trial"
        x="Determination"
        y="Density of the earth (water = 1)"
      />
      <Inspect mode="xy" pin maxDistance={24} />
    </GGPlot>
  );
}

// examples/qq_line/match/Example.svelte
<script lang="ts">
  import {
    GeomQqLine,
    GGPlot,
    Inspect,
    Labs,
    ThemeMinimal,
  } from "@ggts-sh/svelte";

  import { shortSample } from "./data.js";
</script>

<GGPlot data={shortSample} aes={{ sample: "value" }} width={640} height={400}>
  <GeomQqLine linewidth={3.2} alpha={1} aes={{ color: { value: "#1a202c" } }} />
  <ThemeMinimal />
  <Labs
    title="Q–Q reference line"
    subtitle="Line through the sample/theoretical quartile match"
    x="Theoretical quantile"
    y="Sample quantile"
  />
  <Inspect mode="x" pin />
</GGPlot>
