// examples/step/stairs/Example.svelte
<script lang="ts">
  import {
    GeomStep,
    GGPlot,
    Inspect,
    Labs,
    ScaleXContinuous,
    ScaleYContinuous,
    ThemeMinimal,
  } from "@ggts-sh/svelte";

  import { stairVertices } from "./data.js";
</script>

<GGPlot data={stairVertices} aes={{ x: "x", y: "y" }} width={640} height={400}>
  <GeomStep
    direction="hv"
    linewidth={3.4}
    aes={{ color: { value: "#1a202c" } }}
  />
  <ScaleXContinuous limits={[0.5, 5.5]} />
  <ScaleYContinuous limits={[0, 6]} />
  <ThemeMinimal />
  <Labs
    title="Thick staircase"
    subtitle="Five vertices joined horizontal-then-vertical"
    x="x"
    y="y"
  />
  <Inspect mode="x" pin />
</GGPlot>

// examples/vline/cutoff/Example.tsx
"use client";

import { GeomPoint, GeomVline, GGPlot, Inspect, Labs, ThemeMinimal } from "@ggts-sh/react";

import { earthDensity } from "./data.js";

export default function EarthDensityCutoff() {
  return (
    <GGPlot
      data={earthDensity}
      aes={{ x: "trial", y: "density" }}
      width={640}
      height={400}
      ariaLabel="One vertical cutoff"
    >
      <GeomPoint size={2.2} alpha={0.55} />
      <GeomVline xintercept={6.5} linewidth={2.6} aes={{ color: { value: "#d4615c" } }} />
      <ThemeMinimal />
      <Labs
        title="One vertical cutoff"
        subtitle="Wire changed after this trial"
        x="Determination"
        y="Density of the earth (water = 1)"
      />
      <Inspect mode="xy" pin maxDistance={24} />
    </GGPlot>
  );
}
